# Generated by Django 4.2.4 on 2023-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='about',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
