# Generated by Django 4.2.4 on 2023-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_core', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('gastroenterology', 'Gastroenterology'), ('oncology', 'Oncology'), ('pulmonology', 'Pulmonology'), ('obstetrics', 'Obstetrics'), ('pediatrics', 'Pediatrics'), ('ophthalmology', 'Ophthalmology'), ('dermatology', 'Dermatology')], max_length=200),
        ),
    ]
