# Generated by Django 4.2.4 on 2023-08-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_core', '0004_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('NEUROLOGY', 'Neurology'), ('ORTHOPEDICS', 'Orthopedics'), ('GASTROENTEROLOGY', 'Gastroenterology'), ('ONCOLOGY', 'Oncology'), ('PULMONOLOGY', 'Pulmonology'), ('OBSTETRICS', 'Obstetrics'), ('PEDIATRICS', 'Pediatrics'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('DERMATOLOGY', 'Dermatology')], max_length=200),
        ),
    ]
