# Generated by Django 4.2.4 on 2023-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(default='patient.jpg', upload_to='patients_profile_picture'),
        ),
    ]
