# Generated by Django 4.2.4 on 2023-08-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
