# Generated by Django 4.2.4 on 2023-08-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_profile_picture'),
        ('patients', '0006_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date')},
        ),
    ]
