# Generated by Django 4.2.4 on 2023-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default='/icon/doctor.png', upload_to='doctors_profile_picture'),
        ),
    ]
