# Generated by Django 4.2.4 on 2023-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default='doctor.png', upload_to='doctors_profile_picture'),
        ),
    ]
