# Generated by Django 4.2.4 on 2023-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
    ]
